name: Deploy to Github Pages

on: [push]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run validation schema
        run: npx --yes ajv-cli validate -s usecases-info.schema.json -d usecases-info.json
      - name: Run linting
        run: |
          npx --yes js-beautify -f usecases-info.json -k -s 2 -b preserve-inline -n > usecases-info-formatted.json
          cmp usecases-info.json usecases-info-formatted.json > diff.txt
          if [ -s diff.txt ]; then
            echo "Lintting failed. Run command on README.md to fix it and commit changes."
            exit 1
          else
            echo "Lintting OK"   
          fi
